<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="slick, flat, dashboard, bootstrap, admin, template, theme, responsive, fluid, retina">
    <link rel="shortcut icon" href="javascript:;" type="image/png">
      <!--Data Table-->
	    <link href="js/data-table/css/jquery.dataTables.css" rel="stylesheet">
	    <link href="js/data-table/css/dataTables.tableTools.css" rel="stylesheet">
	    <link href="js/data-table/css/dataTables.colVis.min.css" rel="stylesheet">
	    <link href="js/data-table/css/dataTables.responsive.css" rel="stylesheet">
	    <link href="js/data-table/css/dataTables.scroller.css" rel="stylesheet">
	    	
	    	<link href="css/font-awesome.css" rel="stylesheet">
	    	
	    	<!--common style-->
<link href="${pageContext.request.contextPath }/css/style.css" rel="stylesheet" />
<link href="${pageContext.request.contextPath }/css/style-responsive.css" rel="stylesheet" />
	    	
 <title>data table</title>
</head>


<body class="sticky-header">

    

        <!-- body content start-->
        <!-- body content start-->

         	<!--body wrapper start-->
         

                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading ">
                                Convertable Data Table
                                <span class="tools pull-right">
                                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                                    <a class="t-close fa fa-times" href="javascript:;"></a>
                                </span>
                            </header>
	                        <table class="table convert-data-table data-table">
		                        <thead>
			                        <tr>
			                        	<th></th>
			                            <th>
			                                StuID
			                            </th>
			                            <th>
			                                StuName
			                            </th>
			                            <th>
			                                CourseID
			                            </th>
			                            <th>
			                                CourseName
			                            </th>
			                            <th class="hidden-xs"><i class="fa fa-cogs"></i> Action</th>
			                        </tr>
		                        </thead>
		                        <tbody>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                1/6/10
		                            </td>
		                            <td>
		                                Quebec
		                            </td>
		                            <td>
		                                Jones
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                1/23/10
		                            </td>
		                            <td>
		                                Ontario
		                            </td>
		                            <td>
		                                Kivell
		                            </td>
		                            <td>
		                                Binder
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                2/9/10
		                            </td>
		                            <td>
		                                Ontario
		                            </td>
		                            <td>
		                                Jardine
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                           
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                2/26/10
		                            </td>
		                            <td>
		                                Ontario
		                            </td>
		                            <td>
		                                Gill
		                            </td>
		                            <td>
		                                Pen
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                3/15/10
		                            </td>
		                            <td>
		                                Alberta
		                            </td>
		                            <td>
		                                Sorvino
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                4/1/10
		                            </td>
		                            <td>
		                                Quebec
		                            </td>
		                            <td>
		                                Jones
		                            </td>
		                            <td>
		                                Binder
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                4/18/10
		                            </td>
		                            <td>
		                                Ontario
		                            </td>
		                            <td>
		                                Andrews
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                5/5/10
		                            </td>
		                            <td>
		                                Ontario
		                            </td>
		                            <td>
		                                Jardine
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                5/22/10
		                            </td>
		                            <td>
		                                Alberta
		                            </td>
		                            <td>
		                                Thompson
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                6/8/10
		                            </td>
		                            <td>
		                                Quebec
		                            </td>
		                            <td>
		                                Jones
		                            </td>
		                            <td>
		                                Binder
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                6/25/10
		                            </td>
		                            <td>
		                                Ontario
		                            </td>
		                            <td>
		                                Morgan
		                            </td>
		                            <td>
		                                Pencil
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                7/12/10
		                            </td>
		                            <td>
		                                Quebec
		                            </td>
		                            <td>
		                                Howard
		                            </td>
		                            <td>
		                                Binder
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        <tr>
		                        	<td><input type="checkbox" /></td>
		                            <td>
		                                7/29/10
		                            </td>
		                            <td>
		                                Quebec
		                            </td>
		                            <td>
		                                Parent
		                            </td>
		                            <td>
		                                Binder
		                            </td>
		                            <td class="hidden-xs">
				                        <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
				                        <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
				                        <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
				                    </td>
		                        </tr>
		                        </tbody>
	                        </table>
                        </section>
                    </div>

                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading ">
                                Column Visible Data Table
                                <span class="tools pull-right">
                                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                                    <a class="t-close fa fa-times" href="javascript:;"></a>
                                </span>
                            </header>
                            <table class="table colvis-data-table data-table">
	                            <thead>
	                            <tr>
	                                <th>
	                                    OrderDate
	                                </th>
	                                <th>
	                                    Region
	                                </th>
	                                <th>
	                                    Rep
	                                </th>
	                                <th>
	                                    Item
	                                </th>
	                                <th>
	                                    Units
	                                </th>
	                                <th>
	                                    Unit Cost
	                                </th>
	                                <th>
	                                    Total
	                                </th>
	                            </tr>
	                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    1/6/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    95
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    189.05
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    1/23/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    50
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    999.50
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/9/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    36
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    179.64
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/26/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    27
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    539.73
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3/15/10
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    56
                                </td>
                                <td>
                                    2.99
                                </td>
                                <td>
                                    167.44
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/1/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    60
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    299.40
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/18/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    75
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    149.25
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/5/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    90
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    449.10
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/22/10
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Thompson
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    32
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    63.68
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6/8/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    60
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    539.40
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6/25/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Morgan
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    90
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    449.10
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/12/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Howard
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    29
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    57.71
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/29/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Parent
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    81
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    1,619.19
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8/15/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    35
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    174.65
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/1/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Smith
                                </td>
                                <td>
                                    Desk
                                </td>
                                <td>
                                    2
                                </td>
                                <td>
                                    125.00
                                </td>
                                <td>
                                    250.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/18/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    16
                                </td>
                                <td>
                                    15.99
                                </td>
                                <td>
                                    255.84
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/5/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Morgan
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    28
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    251.72
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/22/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    64
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    575.36
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    11/8/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Parent
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    15
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    299.85
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    11/25/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    96
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    479.04
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/12/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Smith
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    67
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    86.43
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/29/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Parent
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    74
                                </td>
                                <td>
                                    15.99
                                </td>
                                <td>
                                    1,183.26
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    1/15/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    46
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    413.54
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/1/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Smith
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    87
                                </td>
                                <td>
                                    15.00
                                </td>
                                <td>
                                    1,305.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/18/11
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    4
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    19.96
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3/7/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    7
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    139.93
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3/24/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    50
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    249.50
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/10/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    66
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    131.34
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/27/11
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Howard
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    96
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    479.04
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/14/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    53
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    68.37
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/31/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    80
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    719.20
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6/17/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Desk
                                </td>
                                <td>
                                    5
                                </td>
                                <td>
                                    125.00
                                </td>
                                <td>
                                    625.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/4/11
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    62
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    309.38
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/21/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Morgan
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    55
                                </td>
                                <td>
                                    12.49
                                </td>
                                <td>
                                    686.95
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8/7/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    42
                                </td>
                                <td>
                                    23.95
                                </td>
                                <td>
                                    1,005.90
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8/24/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Desk
                                </td>
                                <td>
                                    3
                                </td>
                                <td>
                                    275.00
                                </td>
                                <td>
                                    825.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/10/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    7
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    9.03
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/27/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    76
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    151.24
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/14/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Thompson
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    57
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    1,139.43
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/31/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    14
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    18.06
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    11/17/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    11
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    54.89
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/4/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    94
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    1,879.06
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/21/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    28
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    139.72
                                </td>
                            </tr>
                            </tbody>
                            </table>
                        </section>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading ">
                                Responsive Data Table
                                <span class="tools pull-right">
                                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                                    <a class="t-close fa fa-times" href="javascript:;"></a>
                                </span>
                            </header>
                            <table class="table responsive-data-table data-table">
                            <thead>
                            <tr>
                                <th>
                                    OrderDate
                                </th>
                                <th>
                                    Region
                                </th>
                                <th>
                                    Rep
                                </th>
                                <th>
                                    Item
                                </th>
                                <th>
                                    Units
                                </th>
                                <th>
                                    Unit Cost
                                </th>
                                <th>
                                    Total
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    1/6/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    95
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    189.05
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    1/23/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    50
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    999.50
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/9/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    36
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    179.64
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/26/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    27
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    539.73
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3/15/10
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    56
                                </td>
                                <td>
                                    2.99
                                </td>
                                <td>
                                    167.44
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/1/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    60
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    299.40
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/18/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    75
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    149.25
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/5/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    90
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    449.10
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/22/10
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Thompson
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    32
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    63.68
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6/8/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    60
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    539.40
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6/25/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Morgan
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    90
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    449.10
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/12/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Howard
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    29
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    57.71
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/29/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Parent
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    81
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    1,619.19
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8/15/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    35
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    174.65
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/1/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Smith
                                </td>
                                <td>
                                    Desk
                                </td>
                                <td>
                                    2
                                </td>
                                <td>
                                    125.00
                                </td>
                                <td>
                                    250.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/18/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    16
                                </td>
                                <td>
                                    15.99
                                </td>
                                <td>
                                    255.84
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/5/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Morgan
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    28
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    251.72
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/22/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    64
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    575.36
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    11/8/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Parent
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    15
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    299.85
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    11/25/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    96
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    479.04
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/12/10
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Smith
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    67
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    86.43
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/29/10
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Parent
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    74
                                </td>
                                <td>
                                    15.99
                                </td>
                                <td>
                                    1,183.26
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    1/15/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    46
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    413.54
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/1/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Smith
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    87
                                </td>
                                <td>
                                    15.00
                                </td>
                                <td>
                                    1,305.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2/18/11
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    4
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    19.96
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3/7/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    7
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    139.93
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3/24/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    50
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    249.50
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/10/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    66
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    131.34
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    4/27/11
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Howard
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    96
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    479.04
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/14/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    53
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    68.37
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    5/31/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    80
                                </td>
                                <td>
                                    8.99
                                </td>
                                <td>
                                    719.20
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    6/17/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Desk
                                </td>
                                <td>
                                    5
                                </td>
                                <td>
                                    125.00
                                </td>
                                <td>
                                    625.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/4/11
                                </td>
                                <td>
                                    Quebec
                                </td>
                                <td>
                                    Jones
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    62
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    309.38
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    7/21/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Morgan
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    55
                                </td>
                                <td>
                                    12.49
                                </td>
                                <td>
                                    686.95
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8/7/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Kivell
                                </td>
                                <td>
                                    Pen Set
                                </td>
                                <td>
                                    42
                                </td>
                                <td>
                                    23.95
                                </td>
                                <td>
                                    1,005.90
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    8/24/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Desk
                                </td>
                                <td>
                                    3
                                </td>
                                <td>
                                    275.00
                                </td>
                                <td>
                                    825.00
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/10/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Gill
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    7
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    9.03
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    9/27/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Sorvino
                                </td>
                                <td>
                                    Pen
                                </td>
                                <td>
                                    76
                                </td>
                                <td>
                                    1.99
                                </td>
                                <td>
                                    151.24
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/14/11
                                </td>
                                <td>
                                    Alberta
                                </td>
                                <td>
                                    Thompson
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    57
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    1,139.43
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    10/31/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Pencil
                                </td>
                                <td>
                                    14
                                </td>
                                <td>
                                    1.29
                                </td>
                                <td>
                                    18.06
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    11/17/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    11
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    54.89
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/4/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Jardine
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    94
                                </td>
                                <td>
                                    19.99
                                </td>
                                <td>
                                    1,879.06
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    12/21/11
                                </td>
                                <td>
                                    Ontario
                                </td>
                                <td>
                                    Andrews
                                </td>
                                <td>
                                    Binder
                                </td>
                                <td>
                                    28
                                </td>
                                <td>
                                    4.99
                                </td>
                                <td>
                                    139.72
                                </td>
                            </tr>
                            </tbody>
                            </table>
                        </section>
                    </div>

                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">
                            <header class="panel-heading ">
                                Row Details Table
                                <span class="tools pull-right">
                                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                                    <a class="t-close fa fa-times" href="javascript:;"></a>
                                </span>
                            </header>
                            <table class="table data-table row-details-data-table" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Position</th>
                                    <th>Office</th>
                                    <th>Salary</th>
                                </tr>
                                </thead>

                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Position</th>
                                    <th>Office</th>
                                    <th>Salary</th>
                                </tr>
                                </tfoot>
                            </table>
                        </section>
                    </div>

                </div>

            
            <!--body wrapper end-->

        <!-- body content end-->
	
<!-- Placed js at the end of the document so the pages load faster -->
	<script src="js/jquery-1.10.2.min.js"></script>
	<script src="js/jquery-migrate.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/modernizr.min.js"></script>

	<!--Data Table-->
	<script src="js/data-table/js/jquery.dataTables.min.js"></script>
	<script src="js/data-table/js/dataTables.tableTools.min.js"></script>
	<script src="js/data-table/js/bootstrap-dataTable.js"></script>
	<script src="js/data-table/js/dataTables.colVis.min.js"></script>
	<script src="js/data-table/js/dataTables.responsive.min.js"></script>
	<script src="js/data-table/js/dataTables.scroller.min.js"></script>

	
	<!--data table init-->
	<script src="js/data-table-init.js"></script>








</body>
</html>